platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'TextureBase' do
  
  # 2.7 不支持 iOS 8.0
  pod 'Texture', '~> 2.7'
  pod 'SnapKit', '~> 4.2.0'
  pod 'MJRefresh', '~> 3.1.15.7'
  # 5.0 不支持 iOS 9
  # pod 'Kingfisher', '~> 4.10.1'
  pod 'YYWebImage', '~> 1.0.5'
  pod 'JPFPSStatus', '~> 0.1.1'
  pod 'MLeaksFinder', '~> 1.0.0'

  target 'TextureBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextureBaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
