platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'TextureBase' do
  
  # 2.7 不支持 iOS 8.0
  pod 'Texture', '~> 2.7'
  pod 'SnapKit', '~> 4.2.0'

  target 'TextureBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextureBaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
