platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'TextureBase' do

  # 2.7 不支持 iOS 8.0 不支持常用的storyboard、xib、autoLayout
  pod 'Texture', '~> 2.7'
  pod 'SnapKit', '~> 4.2.0'
  pod 'MJRefresh', '~> 3.1.15.7'
  # 5.0 不支持 iOS 9
  pod 'Kingfisher', '~> 4.10.1'
  pod 'YYWebImage', '~> 1.0.5'
  # pod 'JPFPSStatus', '~> 0.1.1'
  pod 'MLeaksFinder', '~> 1.0.0'
  pod 'SDWebImage', '~> 5.0.0-beta3'
  # FPS
  pod 'GDPerformanceView-Swift', '~> 2.0.2'
  pod 'CYLTabBarController', '~> 1.17.22'
  # 视差
  pod 'MXParallaxHeader', '~> 0.6.1'
  pod 'Alamofire', '~> 4.8.0'
  pod 'SwiftyJSON', '~> 4.2.0'
  # 分页查看器
  pod 'JXCategoryView', '~> 1.1.4' # 模拟器滑动切换的时候掉帧
  # pod 'TYPagerController', '~> 2.1.2'
  pod 'TYAttributedLabel', '~> 2.6.6'
  # 轮播广告
  pod 'TYCyclePagerView', '~> 1.1.2'
  # 数据缓存 (数据驱动UI)
  # pod 'DataSources'
  # 没有支持swift 版本
  # pod 'SDCycleScrollView'
  
  
  # 小红点
  # pod 'BadgeSwift', '~> 7.0'
  # Rx相关
  # 运行错误：Command CompileSwiftSources failed with a nonzero exit code
  # 解决办法：https://www.jianshu.com/p/7a3dc4f59fcd  clean 重新编译
  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'
  pod 'Result', '~> 4.0.0'
  pod 'RxAlamofire', '~> 4.3.0'
  pod 'Moya', '~> 12.0.1'
  pod 'Moya/RxSwift', '~> 12.0.1'
  pod 'RxAlamofire', '~> 4.3.0'
  pod 'RxDataSources', '~> 3.1.0'
  # 为了更加方便添加点击事件
  pod 'RxGesture', '~> 2.1.0'
  pod 'ObjectMapper', '~> 3.4.2'
  pod 'HandyJSON', '~> 5.0.0-beta'
  # @dynamicMemberLookup
  # pod 'DynamicJSON', '~> 2.0'
  pod 'Reusable', '~> 4.0.5'
  pod 'SVProgressHUD', '~> 2.2.5'
  # 蓝牙 https://github.com/sheepy1/VisualBlue
  # pod 'RxBluetoothKit'
  # 路由
  pod 'CTMediator', '~> 25'
  # redux
  pod 'ReactorKit', '~> 1.2.1'
  # pod 'RxAppState', '~> 1.3.0'
  pod 'NSObject+Rx', '~> 4.4.1' # 为了使用rx_disposeBag
  # 组件化
  # 骨架
  # pod 'SkeletonView'
  # pod "RxRealm"
  # pod 'RxBluetoothKit'
  # pod 'RxKeyboard'
  # pod 'RxOptional'
  # pod 'RxAnimated'
  
  pod 'Bagel'

  # 学习相关文章
  # https://github.com/CivelXu/UseAsyncDisplayKit-Practice
  # demo不错 https://github.com/tomykho/ios-boilerplate
  # https://github.com/fuhailong/FuASObjet
  # VIPER架构：https://github.com/Zuikyo/ZIKViper
  # https://blog.csdn.net/zhanggenpin/article/details/79095618
  
  # RxSwift 参考地址
  # https://github.com/LinXunFeng/LXFBiliBili
  # https://github.com/sessionCh/RxXMLY
  # 本地组件化 https://github.com/AnyOptional/U17

  target 'TextureBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextureBaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            
            # Fix libstdc++.6在Xcode10编译报错问题
            if target.name == "Pods-SomeTarget"
                xcconfig_path = config.base_configuration_reference.real_path
                xcconfig = File.read(xcconfig_path)
                new_xcconfig = xcconfig.sub('stdc++.6', 'c++')
                
                File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
            end
            update_config config
            if config.build_settings['PRODUCT_NAME'] == 'Result'
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end

# Pod设置 =================================

def update_config (config)
    
    config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
    config.build_settings['SWIFT_VERSION'] = '4.2'
    
    # config.target_attributes["LastSwiftMigration"] = "0830"
    
    if config.name == "Debug" then
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
    end
    
    #    elsif config.name == "Release" then
    #    config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
    #    config.build_settings['SWIFT_VERSION'] = '3.0'
    #    end
end
