platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'TextureBase' do
  
  # 2.7 不支持 iOS 8.0 不支持常用的storyboard、xib、autoLayout
  pod 'Texture', '~> 2.7'
  pod 'SnapKit', '~> 4.2.0'
  pod 'MJRefresh', '~> 3.1.15.7'
  # 5.0 不支持 iOS 9
  pod 'Kingfisher', '~> 4.10.1'
  pod 'YYWebImage', '~> 1.0.5'
  # pod 'JPFPSStatus', '~> 0.1.1'
  pod 'MLeaksFinder', '~> 1.0.0'
  pod 'SDWebImage', '~> 5.0.0-beta3'
  # FPS
  pod 'GDPerformanceView-Swift', '~> 2.0.2'
  pod 'CYLTabBarController', '~> 1.17.22'
  # 视差
  pod 'MXParallaxHeader', '~> 0.6.1'
  pod 'Alamofire', '~> 4.8.0'
  pod 'SwiftyJSON', '~> 4.2.0'
  # 分页查看器
  pod 'JXCategoryView', '~> 1.1.4' # 模拟器滑动切换的时候掉帧
  # pod 'TYPagerController', '~> 2.1.2'
  pod 'TYAttributedLabel', '~> 2.6.6'
  # 轮播广告
  pod 'TYCyclePagerView', '~> 1.1.2'
  # 数据缓存
  # pod 'DataSources'
  
  # Rx相关
  # 运行错误：Command CompileSwiftSources failed with a nonzero exit code
  # 解决办法：https://www.jianshu.com/p/7a3dc4f59fcd
  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'
  pod 'Moya', '~> 12.0.1'
  pod 'Moya/RxSwift', '~> 12.0.1'
  pod 'RxDataSources', '~> 3.1.0'
  pod 'ObjectMapper', '~> 3.4.2'
  pod 'HandyJSON', '~> 4.2.1'
  pod 'RxGesture', '~> 2.1.0'

  # 学习相关文章
  # https://github.com/CivelXu/UseAsyncDisplayKit-Practice
  # demo不错 https://github.com/tomykho/ios-boilerplate
  # https://github.com/fuhailong/FuASObjet
  
  # RxSwift 参考地址
  # https://github.com/LinXunFeng/LXFBiliBili
  # https://github.com/sessionCh/RxXMLY

  target 'TextureBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextureBaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
